name: Integration & Verification

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  inv:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --release --test '*' -- --test-threads=1
